/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINTLN = 5;
  /** RegularExpression Id. */
  int True = 6;
  /** RegularExpression Id. */
  int False = 7;
  /** RegularExpression Id. */
  int LET = 8;
  /** RegularExpression Id. */
  int Id = 9;
  /** RegularExpression Id. */
  int Num = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int NEW = 12;
  /** RegularExpression Id. */
  int REF = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int NOTEQUAL = 18;
  /** RegularExpression Id. */
  int BIG = 19;
  /** RegularExpression Id. */
  int BIGEQUAL = 20;
  /** RegularExpression Id. */
  int SMALLEQUAL = 21;
  /** RegularExpression Id. */
  int SMALL = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int TIMES = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int LPAR = 27;
  /** RegularExpression Id. */
  int RPAR = 28;
  /** RegularExpression Id. */
  int RBR = 29;
  /** RegularExpression Id. */
  int LBR = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int TERM = 32;
  /** RegularExpression Id. */
  int EXCL = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<PRINTLN>",
    "<True>",
    "<False>",
    "<LET>",
    "<Id>",
    "<Num>",
    "\";\"",
    "<NEW>",
    "\":=\"",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\"==\"",
    "\"~=\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";;\"",
    "\"!\"",
  };

}
