/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int LPAR = 10;
  /** RegularExpression Id. */
  int RPAR = 11;
  /** RegularExpression Id. */
  int RBR = 12;
  /** RegularExpression Id. */
  int LBR = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int ARROW = 17;
  /** RegularExpression Id. */
  int COLON = 18;
  /** RegularExpression Id. */
  int TERM = 19;
  /** RegularExpression Id. */
  int BOOL = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int EQUAL = 24;
  /** RegularExpression Id. */
  int NOTEQUAL = 25;
  /** RegularExpression Id. */
  int BIG = 26;
  /** RegularExpression Id. */
  int BIGEQUAL = 27;
  /** RegularExpression Id. */
  int SMALLEQUAL = 28;
  /** RegularExpression Id. */
  int SMALL = 29;
  /** RegularExpression Id. */
  int EQ = 30;
  /** RegularExpression Id. */
  int ASSIGN = 31;
  /** RegularExpression Id. */
  int EXCL = 32;
  /** RegularExpression Id. */
  int LET = 33;
  /** RegularExpression Id. */
  int MUT = 34;
  /** RegularExpression Id. */
  int NEW = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int PRINTLN = 38;
  /** RegularExpression Id. */
  int FUN = 39;
  /** RegularExpression Id. */
  int INTTYPE = 40;
  /** RegularExpression Id. */
  int BOOLTYPE = 41;
  /** RegularExpression Id. */
  int REFTYPE = 42;
  /** RegularExpression Id. */
  int FUNTYPE = 43;
  /** RegularExpression Id. */
  int Id = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"end\"",
    "\";\"",
    "\",\"",
    "\"->\"",
    "\":\"",
    "\";;\"",
    "<BOOL>",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\"==\"",
    "\"~=\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\"=\"",
    "\":=\"",
    "\"!\"",
    "\"let\"",
    "\"mut\"",
    "\"new\"",
    "\"while\"",
    "\"if\"",
    "\"println\"",
    "\"fun\"",
    "\"Int\"",
    "\"Bool\"",
    "\"Ref\"",
    "\"Fun\"",
    "<Id>",
  };

}
